# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sun Apr 24 13:33:49 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1066, 615)
        self.centralwidget = QtGui.QWidget(mainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.videoTab = QtGui.QWidget()
        self.videoTab.setObjectName(_fromUtf8("videoTab"))
        self.videoViewLabel = QtGui.QLabel(self.videoTab)
        self.videoViewLabel.setGeometry(QtCore.QRect(10, 10, 640, 480))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.videoViewLabel.sizePolicy().hasHeightForWidth())
        self.videoViewLabel.setSizePolicy(sizePolicy)
        self.videoViewLabel.setMinimumSize(QtCore.QSize(640, 480))
        self.videoViewLabel.setMaximumSize(QtCore.QSize(960, 720))
        self.videoViewLabel.setObjectName(_fromUtf8("videoViewLabel"))
        self.exitButton = QtGui.QPushButton(self.videoTab)
        self.exitButton.setGeometry(QtCore.QRect(950, 470, 80, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitButton.sizePolicy().hasHeightForWidth())
        self.exitButton.setSizePolicy(sizePolicy)
        self.exitButton.setMinimumSize(QtCore.QSize(80, 30))
        self.exitButton.setObjectName(_fromUtf8("exitButton"))
        self.roverPositionLabel = QtGui.QLabel(self.videoTab)
        self.roverPositionLabel.setGeometry(QtCore.QRect(701, 40, 131, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roverPositionLabel.sizePolicy().hasHeightForWidth())
        self.roverPositionLabel.setSizePolicy(sizePolicy)
        self.roverPositionLabel.setObjectName(_fromUtf8("roverPositionLabel"))
        self.roverPositionValueLabel = QtGui.QLabel(self.videoTab)
        self.roverPositionValueLabel.setGeometry(QtCore.QRect(790, 40, 161, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roverPositionValueLabel.sizePolicy().hasHeightForWidth())
        self.roverPositionValueLabel.setSizePolicy(sizePolicy)
        self.roverPositionValueLabel.setObjectName(_fromUtf8("roverPositionValueLabel"))
        self.cleanUpButton = QtGui.QPushButton(self.videoTab)
        self.cleanUpButton.setGeometry(QtCore.QRect(900, 215, 101, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanUpButton.sizePolicy().hasHeightForWidth())
        self.cleanUpButton.setSizePolicy(sizePolicy)
        self.cleanUpButton.setMinimumSize(QtCore.QSize(80, 30))
        self.cleanUpButton.setObjectName(_fromUtf8("cleanUpButton"))
        self.roverHeadingValueLabel = QtGui.QLabel(self.videoTab)
        self.roverHeadingValueLabel.setGeometry(QtCore.QRect(790, 60, 161, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roverHeadingValueLabel.sizePolicy().hasHeightForWidth())
        self.roverHeadingValueLabel.setSizePolicy(sizePolicy)
        self.roverHeadingValueLabel.setObjectName(_fromUtf8("roverHeadingValueLabel"))
        self.pathSelectSpinBox = QtGui.QSpinBox(self.videoTab)
        self.pathSelectSpinBox.setGeometry(QtCore.QRect(829, 214, 61, 31))
        self.pathSelectSpinBox.setMinimum(1)
        self.pathSelectSpinBox.setMaximum(4)
        self.pathSelectSpinBox.setObjectName(_fromUtf8("pathSelectSpinBox"))
        self.roverStatusLabel = QtGui.QLabel(self.videoTab)
        self.roverStatusLabel.setGeometry(QtCore.QRect(701, 10, 131, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roverStatusLabel.sizePolicy().hasHeightForWidth())
        self.roverStatusLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.roverStatusLabel.setFont(font)
        self.roverStatusLabel.setObjectName(_fromUtf8("roverStatusLabel"))
        self.roverHeadingLabel = QtGui.QLabel(self.videoTab)
        self.roverHeadingLabel.setGeometry(QtCore.QRect(701, 60, 131, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roverHeadingLabel.sizePolicy().hasHeightForWidth())
        self.roverHeadingLabel.setSizePolicy(sizePolicy)
        self.roverHeadingLabel.setObjectName(_fromUtf8("roverHeadingLabel"))
        self.pathViewLabel = QtGui.QLabel(self.videoTab)
        self.pathViewLabel.setGeometry(QtCore.QRect(700, 200, 131, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathViewLabel.sizePolicy().hasHeightForWidth())
        self.pathViewLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pathViewLabel.setFont(font)
        self.pathViewLabel.setObjectName(_fromUtf8("pathViewLabel"))
        self.pathSelectionLabel = QtGui.QLabel(self.videoTab)
        self.pathSelectionLabel.setGeometry(QtCore.QRect(700, 222, 131, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathSelectionLabel.sizePolicy().hasHeightForWidth())
        self.pathSelectionLabel.setSizePolicy(sizePolicy)
        self.pathSelectionLabel.setObjectName(_fromUtf8("pathSelectionLabel"))
        self.cameraFeedControlLabel = QtGui.QLabel(self.videoTab)
        self.cameraFeedControlLabel.setGeometry(QtCore.QRect(700, 130, 171, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cameraFeedControlLabel.sizePolicy().hasHeightForWidth())
        self.cameraFeedControlLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cameraFeedControlLabel.setFont(font)
        self.cameraFeedControlLabel.setObjectName(_fromUtf8("cameraFeedControlLabel"))
        self.refreshViewButton = QtGui.QPushButton(self.videoTab)
        self.refreshViewButton.setGeometry(QtCore.QRect(700, 160, 111, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.refreshViewButton.sizePolicy().hasHeightForWidth())
        self.refreshViewButton.setSizePolicy(sizePolicy)
        self.refreshViewButton.setMinimumSize(QtCore.QSize(80, 30))
        self.refreshViewButton.setObjectName(_fromUtf8("refreshViewButton"))
        self.toggleHomePtsCheckbox = QtGui.QCheckBox(self.videoTab)
        self.toggleHomePtsCheckbox.setGeometry(QtCore.QRect(695, 296, 171, 26))
        self.toggleHomePtsCheckbox.setObjectName(_fromUtf8("toggleHomePtsCheckbox"))
        self.goHomeButton = QtGui.QPushButton(self.videoTab)
        self.goHomeButton.setGeometry(QtCore.QRect(700, 83, 101, 31))
        self.goHomeButton.setObjectName(_fromUtf8("goHomeButton"))
        self.toggleHomePathCheckbox = QtGui.QCheckBox(self.videoTab)
        self.toggleHomePathCheckbox.setGeometry(QtCore.QRect(695, 271, 180, 30))
        self.toggleHomePathCheckbox.setObjectName(_fromUtf8("toggleHomePathCheckbox"))
        self.showObjectDetectionCheckbox = QtGui.QCheckBox(self.videoTab)
        self.showObjectDetectionCheckbox.setGeometry(QtCore.QRect(818, 163, 190, 26))
        self.showObjectDetectionCheckbox.setObjectName(_fromUtf8("showObjectDetectionCheckbox"))
        self.sendNextButton = QtGui.QPushButton(self.videoTab)
        self.sendNextButton.setGeometry(QtCore.QRect(880, 50, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sendNextButton.setFont(font)
        self.sendNextButton.setObjectName(_fromUtf8("sendNextButton"))
        self.stopSendingButton = QtGui.QPushButton(self.videoTab)
        self.stopSendingButton.setGeometry(QtCore.QRect(880, 70, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stopSendingButton.setFont(font)
        self.stopSendingButton.setObjectName(_fromUtf8("stopSendingButton"))
        self.showObjectPathCheckbox = QtGui.QCheckBox(self.videoTab)
        self.showObjectPathCheckbox.setGeometry(QtCore.QRect(695, 250, 190, 26))
        self.showObjectPathCheckbox.setObjectName(_fromUtf8("showObjectPathCheckbox"))
        self.adjustButton = QtGui.QPushButton(self.videoTab)
        self.adjustButton.setGeometry(QtCore.QRect(880, 90, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.adjustButton.setFont(font)
        self.adjustButton.setObjectName(_fromUtf8("adjustButton"))
        self.dest_box = QtGui.QComboBox(self.videoTab)
        self.dest_box.setGeometry(QtCore.QRect(787, 389, 61, 31))
        self.dest_box.setEditable(False)
        self.dest_box.setObjectName(_fromUtf8("dest_box"))
        self.dest_box.addItem(_fromUtf8(""))
        self.dest_box.addItem(_fromUtf8(""))
        self.dest_box.addItem(_fromUtf8(""))
        self.dest_box.addItem(_fromUtf8(""))
        self.dest_box.addItem(_fromUtf8(""))
        self.dest_box.addItem(_fromUtf8(""))
        self.label_candy = QtGui.QLabel(self.videoTab)
        self.label_candy.setGeometry(QtCore.QRect(698, 362, 51, 20))
        self.label_candy.setObjectName(_fromUtf8("label_candy"))
        self.label_dest = QtGui.QLabel(self.videoTab)
        self.label_dest.setGeometry(QtCore.QRect(698, 386, 91, 33))
        self.label_dest.setObjectName(_fromUtf8("label_dest"))
        self.btn_deliver = QtGui.QPushButton(self.videoTab)
        self.btn_deliver.setGeometry(QtCore.QRect(860, 373, 111, 31))
        self.btn_deliver.setObjectName(_fromUtf8("btn_deliver"))
        self.candy_box = QtGui.QComboBox(self.videoTab)
        self.candy_box.setGeometry(QtCore.QRect(787, 356, 61, 31))
        self.candy_box.setObjectName(_fromUtf8("candy_box"))
        self.candy_box.addItem(_fromUtf8(""))
        self.candy_box.addItem(_fromUtf8(""))
        self.candy_box.addItem(_fromUtf8(""))
        self.candy_box.addItem(_fromUtf8(""))
        self.pathViewLabel_2 = QtGui.QLabel(self.videoTab)
        self.pathViewLabel_2.setGeometry(QtCore.QRect(699, 331, 131, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathViewLabel_2.sizePolicy().hasHeightForWidth())
        self.pathViewLabel_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pathViewLabel_2.setFont(font)
        self.pathViewLabel_2.setObjectName(_fromUtf8("pathViewLabel_2"))
        self.tabWidget.addTab(self.videoTab, _fromUtf8(""))
        self.movementTab = QtGui.QWidget()
        self.movementTab.setObjectName(_fromUtf8("movementTab"))
        self.gridLayoutWidget = QtGui.QWidget(self.movementTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(90, 50, 290, 261))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bttn_turnRight = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_turnRight.setObjectName(_fromUtf8("bttn_turnRight"))
        self.gridLayout_2.addWidget(self.bttn_turnRight, 1, 2, 1, 1)
        self.bttn_turnLeft = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_turnLeft.setObjectName(_fromUtf8("bttn_turnLeft"))
        self.gridLayout_2.addWidget(self.bttn_turnLeft, 1, 0, 1, 1)
        self.bttn_forward = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_forward.setObjectName(_fromUtf8("bttn_forward"))
        self.gridLayout_2.addWidget(self.bttn_forward, 0, 1, 1, 1)
        self.bttn_backward = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_backward.setObjectName(_fromUtf8("bttn_backward"))
        self.gridLayout_2.addWidget(self.bttn_backward, 2, 1, 1, 1)
        self.bttn_stop = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_stop.setObjectName(_fromUtf8("bttn_stop"))
        self.gridLayout_2.addWidget(self.bttn_stop, 1, 1, 1, 1)
        self.txt_distance = QtGui.QLineEdit(self.gridLayoutWidget)
        self.txt_distance.setObjectName(_fromUtf8("txt_distance"))
        self.gridLayout_2.addWidget(self.txt_distance, 0, 0, 1, 1)
        self.bttn_testOff = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_testOff.setObjectName(_fromUtf8("bttn_testOff"))
        self.gridLayout_2.addWidget(self.bttn_testOff, 2, 2, 1, 1)
        self.bttn_testOn = QtGui.QPushButton(self.gridLayoutWidget)
        self.bttn_testOn.setObjectName(_fromUtf8("bttn_testOn"))
        self.gridLayout_2.addWidget(self.bttn_testOn, 2, 0, 1, 1)
        self.label_encoders = QtGui.QLabel(self.movementTab)
        self.label_encoders.setGeometry(QtCore.QRect(90, 340, 271, 31))
        self.label_encoders.setText(_fromUtf8(""))
        self.label_encoders.setObjectName(_fromUtf8("label_encoders"))
        self.tabWidget.addTab(self.movementTab, _fromUtf8(""))
        self.testTab = QtGui.QWidget()
        self.testTab.setObjectName(_fromUtf8("testTab"))
        self.proximity_lb = QtGui.QLabel(self.testTab)
        self.proximity_lb.setGeometry(QtCore.QRect(10, 40, 121, 32))
        self.proximity_lb.setObjectName(_fromUtf8("proximity_lb"))
        self.cm_button = QtGui.QPushButton(self.testTab)
        self.cm_button.setGeometry(QtCore.QRect(240, 80, 61, 41))
        self.cm_button.setObjectName(_fromUtf8("cm_button"))
        self.line_value = QtGui.QLabel(self.testTab)
        self.line_value.setGeometry(QtCore.QRect(570, 80, 121, 32))
        self.line_value.setObjectName(_fromUtf8("line_value"))
        self.clear_debug = QtGui.QPushButton(self.testTab)
        self.clear_debug.setGeometry(QtCore.QRect(900, 60, 121, 41))
        self.clear_debug.setObjectName(_fromUtf8("clear_debug"))
        self.distance = QtGui.QLabel(self.testTab)
        self.distance.setGeometry(QtCore.QRect(110, 80, 113, 32))
        self.distance.setObjectName(_fromUtf8("distance"))
        self.proximity_alert = QtGui.QLabel(self.testTab)
        self.proximity_alert.setGeometry(QtCore.QRect(10, 70, 121, 32))
        self.proximity_alert.setObjectName(_fromUtf8("proximity_alert"))
        self.status_lb = QtGui.QLabel(self.testTab)
        self.status_lb.setGeometry(QtCore.QRect(430, 30, 91, 32))
        self.status_lb.setObjectName(_fromUtf8("status_lb"))
        self.curr_line_lb = QtGui.QLabel(self.testTab)
        self.curr_line_lb.setGeometry(QtCore.QRect(570, 30, 251, 32))
        self.curr_line_lb.setObjectName(_fromUtf8("curr_line_lb"))
        self.wait_button = QtGui.QPushButton(self.testTab)
        self.wait_button.setGeometry(QtCore.QRect(320, 90, 81, 41))
        self.wait_button.setObjectName(_fromUtf8("wait_button"))
        self.debug_line = QtGui.QPushButton(self.testTab)
        self.debug_line.setGeometry(QtCore.QRect(730, 80, 151, 41))
        self.debug_line.setObjectName(_fromUtf8("debug_line"))
        self.debug_adc = QtGui.QPushButton(self.testTab)
        self.debug_adc.setGeometry(QtCore.QRect(730, 30, 151, 41))
        self.debug_adc.setObjectName(_fromUtf8("debug_adc"))
        self.curr_dist_lb = QtGui.QLabel(self.testTab)
        self.curr_dist_lb.setGeometry(QtCore.QRect(110, 40, 221, 32))
        self.curr_dist_lb.setObjectName(_fromUtf8("curr_dist_lb"))
        self.raw_button = QtGui.QPushButton(self.testTab)
        self.raw_button.setGeometry(QtCore.QRect(240, 30, 61, 41))
        self.raw_button.setObjectName(_fromUtf8("raw_button"))
        self.status = QtGui.QLabel(self.testTab)
        self.status.setGeometry(QtCore.QRect(430, 70, 111, 32))
        self.status.setObjectName(_fromUtf8("status"))
        self.push_button = QtGui.QPushButton(self.testTab)
        self.push_button.setGeometry(QtCore.QRect(320, 30, 81, 41))
        self.push_button.setObjectName(_fromUtf8("push_button"))
        self.tabWidget.addTab(self.testTab, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1066, 27))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(mainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        mainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtGui.QAction(mainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.actionExit = QtGui.QAction(mainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionToggleFullscreen = QtGui.QAction(mainWindow)
        self.actionToggleFullscreen.setObjectName(_fromUtf8("actionToggleFullscreen"))
        self.actionAboutUs = QtGui.QAction(mainWindow)
        self.actionAboutUs.setObjectName(_fromUtf8("actionAboutUs"))
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionToggleFullscreen)
        self.menuHelp.addAction(self.actionAboutUs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Warehouse Workers", None))
        self.videoViewLabel.setText(_translate("mainWindow", "Video Capture View", None))
        self.exitButton.setText(_translate("mainWindow", "Exit", None))
        self.roverPositionLabel.setText(_translate("mainWindow", "Position:", None))
        self.roverPositionValueLabel.setText(_translate("mainWindow", "position", None))
        self.cleanUpButton.setText(_translate("mainWindow", "Clean Up", None))
        self.roverHeadingValueLabel.setText(_translate("mainWindow", "heading degrees", None))
        self.roverStatusLabel.setText(_translate("mainWindow", "Rover Status:", None))
        self.roverHeadingLabel.setText(_translate("mainWindow", "Heading:", None))
        self.pathViewLabel.setText(_translate("mainWindow", "Path View:", None))
        self.pathSelectionLabel.setText(_translate("mainWindow", "Path Selection", None))
        self.cameraFeedControlLabel.setText(_translate("mainWindow", "Camera Feed Control:", None))
        self.refreshViewButton.setText(_translate("mainWindow", "Refresh View", None))
        self.toggleHomePtsCheckbox.setText(_translate("mainWindow", "Show Home Points", None))
        self.goHomeButton.setText(_translate("mainWindow", "Go Home", None))
        self.toggleHomePathCheckbox.setText(_translate("mainWindow", "Show Path To Home", None))
        self.showObjectDetectionCheckbox.setText(_translate("mainWindow", "Show Object Detection", None))
        self.sendNextButton.setText(_translate("mainWindow", "Send Next", None))
        self.stopSendingButton.setText(_translate("mainWindow", "Stop", None))
        self.showObjectPathCheckbox.setText(_translate("mainWindow", "Show Path To Object", None))
        self.adjustButton.setText(_translate("mainWindow", "Adjust", None))
        self.dest_box.setItemText(0, _translate("mainWindow", "1", None))
        self.dest_box.setItemText(1, _translate("mainWindow", "2", None))
        self.dest_box.setItemText(2, _translate("mainWindow", "3", None))
        self.dest_box.setItemText(3, _translate("mainWindow", "4", None))
        self.dest_box.setItemText(4, _translate("mainWindow", "5", None))
        self.dest_box.setItemText(5, _translate("mainWindow", "6", None))
        self.label_candy.setText(_translate("mainWindow", "Candy", None))
        self.label_dest.setText(_translate("mainWindow", "Destination", None))
        self.btn_deliver.setText(_translate("mainWindow", "Deliver", None))
        self.candy_box.setItemText(0, _translate("mainWindow", "1", None))
        self.candy_box.setItemText(1, _translate("mainWindow", "2", None))
        self.candy_box.setItemText(2, _translate("mainWindow", "3", None))
        self.candy_box.setItemText(3, _translate("mainWindow", "4", None))
        self.pathViewLabel_2.setText(_translate("mainWindow", "Delivery:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.videoTab), _translate("mainWindow", "Warehouse Video Feed", None))
        self.bttn_turnRight.setText(_translate("mainWindow", "Turn Right", None))
        self.bttn_turnLeft.setText(_translate("mainWindow", "Turn Left", None))
        self.bttn_forward.setText(_translate("mainWindow", "Forward", None))
        self.bttn_backward.setText(_translate("mainWindow", "Backward", None))
        self.bttn_stop.setText(_translate("mainWindow", "STOP", None))
        self.bttn_testOff.setText(_translate("mainWindow", "Testing Off", None))
        self.bttn_testOn.setText(_translate("mainWindow", "Testing On", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.movementTab), _translate("mainWindow", "Movement", None))
        self.proximity_lb.setText(_translate("mainWindow", "Proximity:", None))
        self.cm_button.setText(_translate("mainWindow", "cm", None))
        self.line_value.setText(_translate("mainWindow", "00000000", None))
        self.clear_debug.setText(_translate("mainWindow", "Clear Debug", None))
        self.distance.setText(_translate("mainWindow", "0", None))
        self.proximity_alert.setText(_translate("mainWindow", "Safe", None))
        self.status_lb.setText(_translate("mainWindow", "Status:", None))
        self.curr_line_lb.setText(_translate("mainWindow", "Current Line Status:", None))
        self.wait_button.setText(_translate("mainWindow", "Wait", None))
        self.debug_line.setText(_translate("mainWindow", "Debug Line", None))
        self.debug_adc.setText(_translate("mainWindow", "Debug ADC", None))
        self.curr_dist_lb.setText(_translate("mainWindow", "Current Distance:", None))
        self.raw_button.setText(_translate("mainWindow", "raw", None))
        self.status.setText(_translate("mainWindow", "Running", None))
        self.push_button.setText(_translate("mainWindow", "Push", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.testTab), _translate("mainWindow", "Sensors", None))
        self.menuFile.setTitle(_translate("mainWindow", "File", None))
        self.menuView.setTitle(_translate("mainWindow", "View", None))
        self.menuHelp.setTitle(_translate("mainWindow", "Help", None))
        self.actionOpen.setText(_translate("mainWindow", "Open", None))
        self.actionExit.setText(_translate("mainWindow", "Exit", None))
        self.actionToggleFullscreen.setText(_translate("mainWindow", "Toggle Full-screen", None))
        self.actionAboutUs.setText(_translate("mainWindow", "About Us", None))

